### ISSUE TITLE
"Marker stack is empty" message, when going back.

### ISSUE THREAD

**Issue by ReneFroger** [NicolasPetton/xref-js2#6] opened 2016-05-22 17:46 UTC
I use terminal Emacs 25.1.5 on Xubuntu 16.04. When I call `xref-find-definitions` in js2-mode, he finds the right definition.

Then I want get back to the place where I called `xref-find-definitions`. But I get the message 
`user-error: Marker stack is empty`. I couldn't find anything relevant about this message.

Why do I get this message, and how could I solve it?

**Comment by NicolasPetton** [comment] 2016-05-22 19:48
> I use terminal Emacs 25.1.5 on Xubuntu 16.04. When I call `xref-find-definitions` in js2-mode, he finds the right definition.
> 
> Then I want get back to the place where I called `xref-find-definitions`. But I get the message 
> `user-error: Marker stack is empty`. I couldn't find anything relevant
> about this message.

Have you tried with starting Emacs using the -Q option?

**Comment by ReneFroger** [comment] 2016-05-27 17:47
With `emacs -Q`, I get messages about that I'm currently not in a project. I'm not sure how I could fix this.

**Comment by NicolasPetton** [comment] 2016-05-28 10:52
> With `emacs -Q`, I get messages about that I'm currently not in a
> project. I'm not sure how I could fix this.

How did you load xref-js2?  I guess the problem is that vc is not
loaded.

**Comment by ReneFroger** [comment] 2016-06-03 21:32
Version control, you mean? I use .projectile files by the way, which will not being recognized by Emacs. Only by Projectile. I don't use git or any other version control.

**Comment by NicolasPetton** [comment] 2016-06-09 11:59
ReneFroger notifications@github.com writes:

> Version control, you mean? I use .projectile files by the way, which
> will not being recognized by Emacs. Only by Projectile. I don't use
> git or any other version control.

xref-js2 currently uses vc to determine the project root (so there's no
dependency to projectile).  I guess it could optionally use projectile
for that.

**Comment by ReneFroger** [comment] 2016-06-09 12:06
Perhaps it's an useful idea, when there is no vc available, then check on projectile project before the message will be showed up?

**Comment by NicolasPetton** [comment] 2016-06-23 21:42
Yes, that's something that would be nice. Do you want to give it a try?

**Comment by ReneFroger** [comment] 2016-06-23 21:47
Ok, I will try to figure out the xref-js code in the weekend.

**Comment by NicolasPetton** [comment] 2016-08-20 14:38
This has been done in commit 1c76830, I'm closing this issue.

**Closed as completed by NicolasPetton** 2016-08-20 14:38 UTC
